# Dockerfile.backend

# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY backend-dir/package*.json ./

# Install backend dependencies
RUN npm install

# Copy the backend source code
COPY backend .

# Expose the backend port
EXPOSE 3001
EXPOSE 3002

# Start the backend server
CMD ["npm", "start"]
