version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: pAuoZrez73lC
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: neondb
      DB_USER: neondb_owner
      DB_PASSWORD: pAuoZrez73lC
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - postgres
    command: ["start-dev"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3001:3001
      - 3002:3002
    networks:
      - app-network
    depends_on:
      - keycloak
    environment:
      DATABASE_URL: postgresql://neondb_owner:pAuoZrez73lC@postgres/neondb?sslmode=require

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app-network:
